services:
  php:
    build: ./docker/php
    tty: true
    volumes:
      - .:/var/www/html:cached
      - composer_vendor:/var/www/html/vendor
    working_dir: /var/www/html

  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DATYvsn7sH
      MYSQL_DATABASE: architecture
      MYSQL_USER: architecture
      MYSQL_PASSWORD: Ar6rvhPHwQ
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: DATYvsn7sH
    volumes:
      - phpmyadmin-session:/sessions

volumes:
  composer_vendor:
  mysql-data:
  phpmyadmin-session:
